pipeline {
  agent {
        node{
        label 'master'
        customWorkspace 'C/Siddharth/GitWS/${env.BRANCH_NAME}'
        }
      }
//   environment {
// }

  stages {
    stage('AllocateWorkspace'){
      sh 'pwd'
        ws("C/Siddharth/GitWS/${env.BRANCH_NAME}") {
          sh 'pwd'
        }
    }
    stage('InjectEnvVariables') {
      steps {
        print "Workspace :- ${env.WORKSPACE}"
        load "${env.WORKSPACE}/.gitLifePRO/EnvVariables.groovy"
        print "${env.SlnPath}"
        print "${env.SlnName}"
      }
    }
    stage('Build') {
      agent { label 'master' }
      steps {
        print "Workspace :- ${env.WORKSPACE}"
        bat "echo Stage 2 Webhook another try ${env.PROJECT_NAME} - Build # ${env.BUILD_NUMBER} "
        print "${env.SlnPath}"
        print "${env.SlnName}"
        bat "echo BRANCH: ${env.BRANCH_NAME}, COMMIT: ${env.GIT_COMMIT}"
        /*bat "\"${tool 'Default MS Build'}\" \"C:\\Program Files (x86)\\Jenkins\\workspace\\JenkinsPipeAsCode_master\\AdvancedAsyncSourceCode\\AdvancedAsyncDemo.sln\" /p:Configuration=Release /p:Platform=\"Any CPU\" /p:WarningLevel=2;OutDir=\"C:\\Siddharth\\PublishAsyncSourceCode\" /p:ProductVersion=1.0.0.${env.BUILD_NUMBER}"*/
      }
    }
  }
  post {
        always {
  emailext body: '''$PROJECT_NAME - Build # $BUILD_NUMBER - $BUILD_STATUS:

Check console output at $BUILD_URL to view the results.

$BUILD_LOG''', recipientProviders: [developers(), culprits(), brokenBuildSuspects(), upstreamDevelopers()], subject: '$PROJECT_NAME - Build # $BUILD_NUMBER - $BUILD_STATUS!', to: 'sidd456goel@hotmail.com'
}
    }          
}
